<?php
//
//namespace User\Bundle\Entity;
//
//use Doctrine\ORM\EntityRepository;
//use Doctrine\ORM\Tools\Pagination\Paginator;
//
//use Symfony\Component\Security\Core\User\UserProviderInterface;
//use Symfony\Component\Security\Core\User\UserInterface;
//
//
///**
// * StaffRepository
// *
// * This class was generated by the Doctrine ORM. Add your own custom
// * repository methods below.
// */
//class StaffRepository extends EntityRepository
//{
//
//}